theme: jekyll-theme-midnight
name: "SuperSimpleSystem RPG"
description: "a lightweight and minimal rules system for tabletop role play games"
title: "SuperSimpleSystem RPG"
url: "https://theblackwolfpack.github.io/SuperSimpleSystem-RPG/"
markdown: kramdown
