# This is a basic workflow to help you get started with Actions

name: MD to PDF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main

    paths:
      - 'CoreRules/**.md'
      - 'CoreRules/images/**'
      - 'RuleSets/**/**.md'
      - 'RuleSets/**/images/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  corerules:
    # name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: CoreRules
          output_dir: processedCoreRules
          images_dir: CoreRules/images
          # for example <img src="./images/file-name.png">
          image_import: ./images
          # Default is true, can set to false to only get PDF files
          # build_html: false
          theme: CoreRules/process.css
          template: CoreRules/process.html
      - uses: actions/upload-artifact@v1
        with:
          name: CoreRules
          path: processedCoreRules
  ruleset_Fantasy:
    # name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: RuleSets/Fantasy
          output_dir: processedRulesetFantasy
          images_dir: RuleSets/Fantasy/images
          # for example <img src="./images/file-name.png">
          image_import: ./images
          # Default is true, can set to false to only get PDF files
          # build_html: false
          theme: RuleSets/Fantasy/process.css
          template: RuleSets/Fantasy/process.html
      - uses: actions/upload-artifact@v1
        with:
          name: Ruleset_Fantasy
          path: processedRulesetFantasy
