# This is a basic workflow to help you get started with Actions

name: MD to PDF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - action_test

    paths:
      - 'CoreRules/**.md'
      - 'CoreRules/images/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  corerules:
    # name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: CoreRules
          output_dir: processed/CoreRules
          images_dir: CoreRules/images
          # for example <img src="./images/file-name.png">
          image_import: ./images
          # Default is true, can set to false to only get PDF files
          # build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: CoreRules
          path: processed/CoreRules
